version: '3.8'
services:
  nginx-react:
    image: fe-hack:latest
    container_name: fe-hack
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      NODE_ENV: production
