version: '3.8'
services:
  react:
    ports:
      - "5173:5173"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/build
      - .:/build/node_modules
    networks:
      - frontend
    command: ["npm", "run", "dev"]
networks:
  frontend: